# Generated by Django 2.1.2 on 2018-10-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181006_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='interests',
        ),
        migrations.AddField(
            model_name='blogger',
            name='hobbies',
            field=models.ManyToManyField(related_name='hobbies', to='accounts.Subject'),
        ),
    ]
