# Generated by Django 2.1.2 on 2018-10-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181008_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='reader',
            name='interests',
            field=models.ManyToManyField(related_name='interests', to='accounts.Choices'),
        ),
    ]
