# Generated by Django 2.1.2 on 2018-10-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181008_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='color',
        ),
        migrations.AlterField(
            model_name='reader',
            name='interests',
            field=models.ManyToManyField(related_name='interests', to='accounts.Subject'),
        ),
    ]
